# Generated by Django 3.2 on 2021-06-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210609_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationuse',
            name='satisfies',
        ),
    ]
