# Generated by Django 3.2 on 2021-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_locationuse_satisfies'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlocation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
