# Generated by Django 3.2 on 2021-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20210610_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestequipment',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestservices',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
