# Generated by Django 3.2 on 2021-06-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_form_editable'),
        ('resources', '0006_auto_20210610_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formfeedbackid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_feedback', to='forms.form'),
        ),
        migrations.AlterField(
            model_name='event',
            name='formsignupid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_signup', to='forms.form'),
        ),
    ]
