# Generated by Django 3.2 on 2021-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210611_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestype',
            name='name',
            field=models.CharField(blank=True, max_length=126, null=True, unique=True),
        ),
    ]
