# Generated by Django 3.2 on 2021-07-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20210629_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemuse',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.event'),
        ),
        migrations.AlterField(
            model_name='locationuse',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.event'),
        ),
        migrations.AlterField(
            model_name='register',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.event'),
        ),
        migrations.AlterField(
            model_name='requestequipment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.event'),
        ),
        migrations.AlterField(
            model_name='requestlocation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.event'),
        ),
        migrations.AlterField(
            model_name='requestservices',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.event'),
        ),
        migrations.AlterField(
            model_name='serviceuse',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resources.event'),
        ),
    ]
