# Generated by Django 3.2 on 2021-06-09 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formAnswers', to='resources.event'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.form'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='forms.answerstatus'),
        ),
        migrations.AddField(
            model_name='form',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='forms.formtype'),
        ),
    ]
