# Generated by Django 3.2 on 2021-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='hide_question_numbers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='hide_section_numbers',
            field=models.BooleanField(default=False),
        ),
    ]
