# Generated by Django 3.2 on 2021-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20210609_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='redirect',
            field=models.CharField(default=3, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='redirect_delay',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='submit_message',
            field=models.CharField(default=3, max_length=256),
            preserve_default=False,
        ),
    ]
