# Generated by Django 3.2 on 2021-06-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210609_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='forms.formtype'),
            preserve_default=False,
        ),
    ]
