# Generated by Django 3.2 on 2021-06-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='redirect',
            field=models.CharField(default='/consult_events', max_length=256),
        ),
    ]
