# Generated by Django 3.2 on 2021-06-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_form_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
