# Generated by Django 3.2 on 2021-06-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_alter_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='forms.formtype'),
        ),
    ]
