# Generated by Django 3.2 on 2021-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_form_submit_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='authentication_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
