# Generated by Django 3.2 on 2021-07-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210611_1253'),
        ('forms', '0016_formanswer_authentication_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=128)),
                ('signature1', models.CharField(blank=True, max_length=64, null=True)),
                ('signature2', models.CharField(blank=True, max_length=64, null=True)),
                ('signatureImage1', models.ImageField(blank=True, null=True, upload_to='signatures')),
                ('signatureImage2', models.ImageField(blank=True, null=True, upload_to='signatures')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='resources.event')),
            ],
        ),
    ]
