# Generated by Django 3.2 on 2021-07-06 16:12

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='authentication_key',
            field=models.CharField(default=forms.models.FormAnswer.authentication_key_default, max_length=32),
        ),
    ]
