# Generated by Django 3.2 on 2021-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20210706_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
