# Generated by Django 3.2 on 2021-07-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_auto_20210706_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
