# Generated by Django 3.2 on 2021-07-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_alter_form_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formanswer',
            options={'permissions': [('update_status', 'Can update submission status'), ('request_auth', 'Can request an authentication_key')]},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
