# Generated by Django 3.2 on 2021-07-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_alter_formanswer_options'),
        ('forms', '0024_auto_20210707_0139'),
    ]

    operations = [
    ]
