from django.urls import path

from . import views

urlpatterns = [
    path('equipment', views.equipment, name='equipment'),
    path('equipmentList', views.equipmentList, name='equipmentList'),
    path('equipmentDelete/<int:id>', views.equipmentDelete, name='equipmentDelete'),
    path('equipmentView/<int:id>', views.equipmentView, name='equipmentView'),
	path('equipmentEdit/<int:id>', views.equipmentEdit, name='equipmentEdit'),
    path('locationType', views.locationType, name='locationType'),
    path('locationTypeList', views.locationTypeList, name='locationTypeList'),
    path('locationTypeDelete/<int:id>', views.locationTypeDelete, name='locationTypeDelete'),
    path('locationTypeView/<int:id>', views.locationTypeView, name='locationTypeView'),
    path('locationTypeEdit/<int:id>', views.locationTypeEdit, name='locationTypeEdit'),    
    path('location', views.location, name='location'),
    path('locationList', views.locationList, name='locationList'),
    path('locationDelete/<int:id>', views.locationDelete, name='locationDelete'),
    path('locationView/<int:id>', views.locationView, name='locationView'),
    path('locationEdit/<int:id>', views.locationEdit, name='locationEdit'),    
    path('servicesType', views.servicesType, name='servicesType'),
    path('servicesTypeList', views.servicesTypeList, name='servicesTypeList'),
    path('servicesTypeDelete/<int:id>', views.servicesTypeDelete, name='servicesTypeDelete'),    
    path('servicesTypeView/<int:id>', views.servicesTypeView, name='servicesTypeView'),
    path('servicesTypeEdit/<int:id>', views.servicesTypeEdit, name='servicesTypeEdit'),    
    path('campusAdd', views.campusAdd, name='campus'),
    path('campusList', views.campusList, name='campusList'),
    path('campusDelete/<int:id>', views.campusDelete, name='campusDelete'),
	path('campusView/<int:id>', views.campusView, name='campusView'),
    path('campusEdit/<int:id>', views.campusEdit, name='campusEdit'),
    path('buildingAdd', views.buildingAdd, name='building'),
    path('buildingList', views.buildingList, name='buildingList'),
    path('buildingDelete/<int:id>', views.buildingDelete, name='buildingDelete'),
	path('buildingView/<int:id>', views.buildingView, name='buildingView'),
    path('buildingEdit/<int:id>', views.buildingEdit, name='buildingEdit'),
    path('itemAdd', views.itemAdd, name='itemAdd'),
    path('itemList', views.itemList, name='itemList'),
    path('itemDelete/<int:id>', views.itemDelete, name='itemDelete'),
    path('itemView/<int:id>', views.itemView, name='itemView'),
    path('itemEdit/<int:id>', views.itemEdit, name='itemEdit'),
	path('serviceAdd', views.serviceAdd, name='serviceAdd'),
    path('serviceList', views.serviceList, name='serviceList'),
    path('serviceDelete/<int:id>', views.serviceDelete, name='serviceDelete'),
    path('serviceView/<int:id>', views.serviceView, name='serviceView'),
    path('serviceEdit/<int:id>', views.serviceEdit, name='serviceEdit'),
    path('list_buildings', views.list_buildings, name='list_buildings'),


]